const SERVER_URL = 'https://mandarin.api.weniv.co.kr';
const IMG_UPLOAD_MAXCOUNT = 3;

// 로그인 기능 완료시 삭제 예정
const USER_TOKEN =
	'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDk5NGNmMTdhZTY2NjU4MTg0Y2QyMCIsImV4cCI6MTY2MzYxMDYyMCwiaWF0IjoxNjU4NDI2NjIwfQ.MGJaNjVD65OOThNnwj_EOd-mlWnj-EsYkIZlBoPOF2g';
const USER_ACCOUNTNAME = 'bookduk';

// const POST_ID = '62d6402a82fdcc712f4d6569';

export { SERVER_URL, USER_TOKEN, IMG_UPLOAD_MAXCOUNT, USER_ACCOUNTNAME };
